config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # The priority is based upon order
  # of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  root 'pages#home'
  get 'signup', to: 'users#new'
  get 'userhome', to: 'users#home'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route
  # (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/task.rb
class Task < ActiveRecord::Base
  # Model for task
  belongs_to :user
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
  validates :deadline_cannot_be_in_the_past, presence: true

  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, "can't be in the past")
    end
  end
  enum status: [:created, :inprogress, :completed]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :all_users

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def all_users
    User.all
  end

  def require_user
    unless logged_in?
      flash[:danger] = 'You must be logged in to perform that action'
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to tasks_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def home
    @user = session[:user_id]
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to '/userhome'
    else
      flash.now[:danger] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out'
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:new, :edit, :create, :update, :destroy]
  before_action :require_same_user, only: [:edit,  :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.paginate(page: params[:page])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    @task.user = User.find(task_params['user_id']) if task_params['user_id']
    if @task.save
      flash[:success] = 'Task was successfully created.'
      redirect_to task_path(@task)

    else
      render 'new'
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    if @task.update(task_params)
      flash[:notice] = 'Task was successfully updated.'
      redirect_to task_path(@task)
    else
      render 'edit'
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy

    flash[:danger] = 'Task was successfully destroyed.'
    redirect_to tasks_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:description, :user_id, :status, :deadline)
  end

  def require_same_user
    if current_user != @task.user && !current_user.admin?
      flash[:danger] = 'You can edit or delete your own tasks'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def home
    @user = session[:user_id]
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.username}"
      redirect_to '/userhome'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account was updated'
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  def show
    @user_tasks = @user.tasks.paginate(page: params[:page])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = 'User and all tasks created by user have been deleted'
    redirect_to users_path
  end

  def set_user
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = 'You can only edit your account'
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = 'only Admin users can perform that action'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
#
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  # Automatice generation of task helper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg|%>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
<% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Commutatus", root_path, class: "navbar-brand", id: "logo" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "To-do-lists", tasks_path %></li>
        <li><%= link_to "New Task", userhome_path %></li>
        <li><%= link_to "Users", users_path %></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <% else%>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation'%>
  <%= render 'layouts/messages'%>
  <div class="container">
  <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>Task management</h1>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%= pluralize(obj.errors.count, "error")%>
                    prohibited this article from being saved:
                </h2>
                <div class="panel-body">
                    <ul><%  obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/tasks/_form.html.erb
<%= render 'shared/errors', obj: @task %>
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@task, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :description %>
        </div>
        <div class="col-sm-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Task....." %>
        </div>
    </div>
     <div class="form-group">
        <div class="control-label col-sm-2">
            <label>Assign to: </label>
        </div>
        <div class="col-sm-8">
        <%= f.select :user_id, all_users.collect { |p| [ p.username, p.id] }, include_blank: true %>
        </div>

    </div>
    <% if params[:action] == 'new'%>
     <div class="form-group">
        <div class="control-label col-sm-2">
            <label>Deadline</label>
        </div>
        <div class="col-sm-8">
          <%= f.date_select :deadline, :start_year=>2016 %>
        </div>

    </div>
    <%  end %>
    <% if params[:action] == 'edit'%>
     <div class="form-group">
        <div class="control-label col-sm-2">
            <label>Status</label>
        </div>
        <div class="col-sm-8">
          <%= f.select :status, Task.statuses.keys,  include_blank: true %>
        </div>

    </div>
    <%  end %>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
        [ <%= link_to "Cancel request and return to Task listing", tasks_path %> ]
    </div>
    </div>
</div>

app/views/tasks/_task.html.erb
<div class="container bootstrap snippet">

  <div class="row">

    <ul class="notes">

      <% obj.each do |task| %>

      <li style="display: inline-block;">
        <div class=<%= if(task.id%2 == 0)
        'rotate-1'
        else
          'rotate-2'
        end %> >
          <span class= "pull-left btn btn-danger btn-xs">

          <%= task.deadline %>
          </span>
          <% if logged_in? && (current_user == task.user || current_user.admin?) %>

          <%= link_to  task_path(task), method: :delete,
                                                                      data: {confirm: "Are you sure you want to delete the article?"},
                                                                      class: "pull-right"  do %>
          <i class="glyphicon glyphicon-remove"></i>
          <% end %>
          <% end %>
          <p class="task-color"><%= link_to truncate(task.description, length: 26), task_path(task) %></p>
          <hr>
          <small>Assigned to: <strong><%= task.user.username if task.user%></strong>,
            <%= time_ago_in_words(task.created_at)%> ago,
            last updated: <strong><%= time_ago_in_words(task.updated_at)%> ago</strong></small>
          <hr>
          <small  class= "btn btn-<%= if task.status == 'created'
          'primary'
          elsif task.status == 'inprogress'
            'warning'
          elsif task.status == 'completed'
          'success'
          end %>
          pull-right pull-down"><%= task.status %></small>
        </div>
      </li>
      <% end %>
    </ul>

  </div>

</div>

app/views/tasks/edit.html.erb
<h1 align="center">Edit task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1 align="center">Listing tasks</h1>
<div align="center">

  <%= will_paginate %>
</div>
<%= render 'task', obj: @tasks %>
<div align="center">
  <%= will_paginate %>

</div>

app/views/tasks/new.html.erb
<h1 style="margin-left: 5%;" align="center">Create a task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div style="margin-top: 25px; padding:10px; border: none; background-color: rgba(255, 255, 255, 0.51);"class="panel panel-default panel-xs">
  <h4 style="margin-left: 50%"><strong>Description:</strong></h4>
  <hr>
  <div style="margin-left: 25%"class="panel-body"> <%= simple_format(@task.description) %>
  <div class="row">
    <div class= "article-actions">
    <% if logged_in? && (current_user == @task.user || current_user.admin?)%>
          <%= link_to "Edit the task", edit_task_path(@task), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this task", task_path(@task), method: :delete,
                                                                    data: {confirm: "Are you sure you want to delete the task?"},
                                                                    class: "btn btn-xs btn-danger" %>
    <% end %>

    <%= link_to "View all tasks", tasks_path, class: "btn btn-xs btn-success" %>
  </div>
    <div style="padding: 2%" class=" col-md-offset-4 pull-right">
      Create by:
      <br>
      <strong><%= link_to @task.user.username, user_path(@task.user) %></strong>
    </div>
  </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :username %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter username" %>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :email %>
        </div>
        <div class="col-sm-8">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter email"%>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :password %>
        </div>
        <div class="col-sm-8">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password"%>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
        </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
        [ <%= link_to "Cancel request and return to Task listing", tasks_path %> ]
    </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>


<%= render 'form' %>

app/views/users/home.html.erb
<div class="task-new">
  <%= link_to new_task_path do %>
  <button type="button" class="btn btn-success  big">
  <i class="glyphicon glyphicon-plus-sign "></i>
  <p class="task-size">Create new task</p>
  </button>
  <% end %>

  <%= link_to user_path(@user) do %>
  <button type="button" class="btn btn-info  big">
  <i class="glyphicon glyphicon-list "></i>
  <p class="task-size">List of created tasks</p>
  </button>
  <% end %>


</div>

app/views/users/index.html.erb
<h1 style="margin-left:5%;" align="center">All members of team</h1>
<div align="center">
<%= will_paginate %>
<% @users.each do |user|%>

<div class="list-group">
  <li style="text-align: center;"class="list-group-item list-group-item-action">

    <%= link_to user.username.camelize , user_path(user), :style =>  " color: #0c0b0b;" %>
    <span style="margin-right: 50px;" class= " pull-right">
    <%= pluralize(user.tasks.count, "task") if user.tasks  %>
    </span>

  </li>


</div>



<%= will_paginate %>
<% end %>
</div>

app/views/users/new.html.erb
<h1 aign="center">Signup</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="show-task">Welcome to <%= @user.username %>'s tasks</h1>
<div class="center">
  <%= will_paginate @user_tasks %>
</div>
<%= render 'tasks/task', obj: @user_tasks %>

<div class="center">
  <%= will_paginate @user_tasks %>
</div>